name:                applicative
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  applicative-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - applicative

tests:
  applicative-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - applicative
    - hspec
    - checkers
    - QuickCheck
